Update LAPS Decrypt Password Script

diff --git a/LAPS Decrypt Password Script b/LAPS Decrypt Password Script
--- a/LAPS Decrypt Password Script
+++ b/LAPS Decrypt Password Script
@@ -40,19 +40,29 @@ token=$(curl -s -H "Content-Type: application/json" -H "Authorization: Basic ${e
 	
 # Pop up for Device name
 	
-name=$(dialog \
+message=$(dialog \
 --bannerimage "/Library/.LAPS/Branding/Wallpapers/GenericLapsBanner.png" \
 --title "none" \
 --icon "/Library/.LAPS/Branding/Icons/lock icon.png" --iconsize 100 \
---message "Please enter the name of the device you wish to see the LAPS password for." \
+--message "Please enter the name of the device you wish to see the LAPS password for. \n\n You must also provide a reason for viewing the LAPS Password for auditing." \
 --messagefont "name=Arial,size=17" \
 --button1text "Continue" \
 --button2text "Quit" \
---textfield "Device name" \
+--textfield "Device name,required" \
+--textfield "Reason,required" \
 --ontop \
---small \
---moveable \
-| awk '{print $4}')
+--regular \
+--json \
+--moveable
+)
+			
+name=$(echo $message | awk -F '"Device name" : "' '{print$2}' | awk -F '"' '{print$1}')
+reason=$(echo $message | awk -F '"Reason" : "' '{print$2}' | awk -F '"' '{print$1}') # Thanks to ons-mart https://github.com/ons-mart
+			
+if [[ $name == "" ]] || [[ $reason == "" ]]; then
+	echo "Aborting"
+	exit 1
+fi			
 		
 # Grab decryption key for password
 cryptkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i CryptKey | tr '"' ' ' | awk '{print $16}')
@@ -68,7 +78,7 @@ dialog \
 --bannerimage "/Library/.LAPS/Branding/Wallpapers/GenericLapsBanner.png" \
 --title "none" \
 --icon "/Library/.LAPS/Branding/Icons/Open Lock Icon.png" --iconsize 100 \
---message "The LAPS Password for $name is $passwd \n\n This message will close after 10seconds." \
+--message "The LAPS Password for $name is: $passwd \n\n This message will close after 10seconds." \
 --messagefont "name=Arial,size=17" \
 --timer \
 --ontop \
@@ -77,6 +87,9 @@ dialog \
 
 echo "The LAPS Password for $name was viewed by $CURRENT_USER on $DEVICE"
 echo "The LAPS Password for $name was viewed by $CURRENT_USER on $DEVICE" >> "$LAPSLOG"
+echo "Reason for viewing password: $reason"
+echo "Reason for viewing password: $reason" >> "$LAPSLOG"
+
 
 if [[ $6 == "True" ]] || [[ $6 == "true" ]]; then
 	echo "Password rotation has been set to True. Password for $name will be reset at next login"
