Update LAPS Create & Cycle Password Script

diff --git a/LAPS Create & Cycle Password Script b/LAPS Create & Cycle Password Script
--- a/LAPS Create & Cycle Password Script
+++ b/LAPS Create & Cycle Password Script
@@ -90,7 +90,14 @@ if dscl . read /Groups/admin | grep $4; then
 	OLDpasswd=$(echo $OLDkey | openssl enc -aes-256-cbc -md sha512 -a -d -salt -pass pass:$OLDsecret)
 		
 		sysadminctl -adminUser $4 -adminPassword $OLDpasswd -resetPasswordFor $4 -newPassword $finalpass
-		dscl /Local/Default -authonly $4 $finalpass
+
+		pswdCheck=$(dscl /Local/Default -authonly $4 $finalpass)
+		if echo $pswdCheck | grep eDSAuthFailed; then
+		echo "Password validation failed."
+		exit 1
+		fi
+		echo "Password validated"
+		
 		rm -rf /Users/$4/Library/Keychains/*
 		
 	# Check Password reset Extension attribute
