Update LAPS Create & Cycle Password Script

diff --git a/LAPS Create & Cycle Password Script b/LAPS Create & Cycle Password Script
--- a/LAPS Create & Cycle Password Script
+++ b/LAPS Create & Cycle Password Script
@@ -2,8 +2,8 @@
 #
 # Author  : Perry Driscoll - https://github.com/PezzaD84
 # Created : 31/1/2022
-# Updated : 12/7/2023
-# Version : v2.2.3
+# Updated : 26/9/2023
+# Version : v2.2.4
 #
 ############################################################################
 # Description:
@@ -96,7 +96,7 @@ if [ -f "$LAPSLOG" ]; then
 				-H "Accept: application/xml" \
 				-H "Authorization:Bearer ${token}" \
 				-d "<computer><extension_attributes><extension_attribute><id>$secretID</id><name>LAPS Secret</name><type>String</type><value></value></extension_attribute></extension_attributes></computer>"
-				
+					
 					############################################################################
 					# LAPS Account Removal
 					############################################################################
@@ -140,16 +140,14 @@ fi
 
 if [ -f "$LAPSLOG" ]; then
 	echo "Log already exists. Continuing setup....."
-        echo -e "=================================================================\n============ LAPS Account cycled `date '+%d/%m/%Y %T'` ============\n================================================================="
-	echo -e "=================================================================\n============ LAPS Account cycled `date '+%d/%m/%Y %T'` ============\n=================================================================" >> "$LAPSLOG"
+	echo -e "=================================================================\n============ LAPS Account cycled `date '+%d/%m/%Y %T'` ============\n=================================================================" | tee -a "$LAPSLOG"
 else
 	# Check for existing duplicate admin accounts
 	LAPSaccount="$4"
 	echo "Checking for existing local admin account $LAPSaccount...."
 	
 	if dscl . -list /Users | grep -x -i "$LAPSaccount"; then
-		echo "Local admin account already exists with the same name. Please rename your LAPSaccount or delete the local admin account before configuring LAPS."
-		echo "Local admin account already exists with the same name. Please rename your LAPSaccount or delete the local admin account before configuring LAPS." >> "$LAPSLOG"
+		echo "Local admin account already exists with the same name. Please rename your LAPSaccount or delete the local admin account before configuring LAPS." | tee -a "$LAPSLOG"
 		osascript -e 'Display dialog "An account with the same name pre-exists on this device.\n\nPlease remove the existing local account or rename the LAPS account.\n\nExisting Account: '$LAPSaccount'" buttons {"Quit"} default button 1 with title "LAPS Setup failure" with icon alias "System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:AlertStopIcon.icns"'
 		exit 1
 	fi
@@ -159,8 +157,7 @@ else
 	mkdir -p /Library/.LAPS/Logs/Failures
 	touch "$LAPSLOG"
 	echo "LAPS Log created. Continuing setup....."
-	echo -e "=================================================================\n=========== LAPS Account creation `date '+%d/%m/%Y %T'` ===========\n================================================================="
-	echo -e "=================================================================\n=========== LAPS Account creation `date '+%d/%m/%Y %T'` ===========\n=================================================================" >> "$LAPSLOG"
+	echo -e "=================================================================\n=========== LAPS Account creation `date '+%d/%m/%Y %T'` ===========\n=================================================================" | tee -a "$LAPSLOG"
 fi
 
 ############################################################################
@@ -169,8 +166,7 @@ fi
 
 length=$7
 
-echo "Password length has been set to $length characters"
-echo "Password length has been set to $length characters" >> "$LAPSLOG"
+echo "Password length has been set to $length characters" | tee -a "$LAPSLOG"
 
 chars='@#$%&_+=!?'
 
@@ -181,8 +177,7 @@ specialchar=$8
 if $specialchar == true ; then
 	password=$(openssl rand -base64 32 | tr -d '/' | tr -d '\' | tr -d ' ' | cut -c -$length | cut -c 2-)
 	finalpass=$password$spchar
-    echo "A Special character has been set in the password"
-	echo "A Special character has been set in the password" >> "$LAPSLOG"
+	echo "A Special character has been set in the password" | tee -a "$LAPSLOG"
 else
 	password=$(openssl rand -base64 32 | tr -d '/' | tr -d '\' | tr -d ' ' | cut -c -$length )
 	finalpass=$password
@@ -205,14 +200,22 @@ cryptkey=$(echo "$finalpass" | openssl enc -aes-256-cbc -md sha512 -a -salt -pas
 ############################################################################
 
 if dscl . read /Groups/admin | grep $4; then
-	echo "$4 has already been created and is a local admin. Resetting local admin password...."
-	echo "$4 has already been created and is a local admin. Resetting local admin password...." >> "$LAPSLOG"
+	echo "$4 has already been created and is a local admin. Resetting local admin password...." | tee -a "$LAPSLOG"
 	
 	TITLE="LAPS Password Reset"
 	
 	############################################################################
 	# Reset local admin password
 	############################################################################
+	
+	ACTIVESESH=$(w | grep $4)
+	
+	if [[ $ACTIVESESH == "" ]]; then
+		echo "No active session for $4. Continuing to reset password" | tee -a "$LAPSLOG"
+	else
+		echo "There is an active session running for $4. Password will be reset later." | tee -a "$LAPSLOG"
+		exit 1
+	fi
 	
 	serial=$(system_profiler SPHardwareDataType | awk '/Serial Number/{print $4}')
 	OLDkey=$(curl -s -X "GET" "$6/JSSResource/computers/serialnumber/$serial/subset/extension_attributes" -H 'Accept: application/json' -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep CryptKey | tr '"' ' ' | awk '{print $16}')
@@ -223,18 +226,15 @@ if dscl . read /Groups/admin | grep $4; then
 
 		pswdCheck=$(dscl /Local/Default -authonly $4 $finalpass)
 		if echo $pswdCheck | grep eDSAuthFailed; then
-		echo "Password validation failed. Please re-run the LAPS policy. If the problem persists please raise a ticket."
-		echo "Password validation failed. Please re-run the LAPS policy. If the problem persists please raise a ticket." >> "$LAPSLOG"
+		echo "Password validation failed." | tee -a "$LAPSLOG"
         exit 1
 		else
-		echo "Password validated"
-		echo "Password validated" >> "$LAPSLOG"
+		echo "Password validated" | tee -a "$LAPSLOG"
 		fi
         
 		rm -rf /Users/$4/Library/Keychains/*
 else
-	echo "$4 does not exist. Creating local admin now"
-	echo "$4 does not exist. Creating local admin now" >> "$LAPSLOG"
+	echo "$4 does not exist. Creating local admin now" | tee -a "$LAPSLOG"
 	
 	TITLE="LAPS Account Created"
 
@@ -252,8 +252,7 @@ sudo sysadminctl \
 sleep 5
 
 if dscl . read /Groups/admin | grep $4; then
-	echo "LAPS Account created Successfully"
-	echo "LAPS Account created Successfully" >> "$LAPSLOG"
+	echo "LAPS Account created Successfully" | tee -a "$LAPSLOG"
 fi
 
 ############################################################################
@@ -337,31 +336,22 @@ secretID=$(curl -s -X "GET" "$6/JSSResource/computers/serialnumber/$serial/subse
 	ID=$(curl -s -X GET "$6/JSSResource/computers/serialnumber/$serial" -H 'Accept: application/xml' -H "Authorization:Bearer ${token}" | tr '<' '\n' | grep -m 1 id | tr -d 'id>')	
 
 	if [[ $cryptkey == "" ]] || [[ $secretkey == "" ]]; then
-		
-		echo "Device serial is $serial"
-		echo "JAMF ID is $ID"
-		echo "LAPS Configuration has failed"
-		echo "Device serial is $serial" >> "$LAPSLOG"
-		echo "JAMF ID is $ID" >> "$LAPSLOG"
-		echo "LAPS Configuration has failed" >> "$LAPSLOG"
+
+		echo "Device serial is $serial" | tee -a "$LAPSLOG"
+		echo "JAMF ID is $ID" | tee -a "$LAPSLOG"
+		echo "LAPS Configuration has failed" | tee -a "$LAPSLOG"
 		RESULT="There was an error. Please check LAPS log for more info."
 		if [[ $cryptkey == "" ]]; then
-			echo "Cryptkey has not been successfully configured"
-			echo "Cryptkey has not been successfully configured" >> "$LAPSLOG"
+			echo "Cryptkey has not been successfully configured" | tee -a "$LAPSLOG"
 		fi
 		if [[ $secretkey == "" ]]; then
-			echo "SecretKey has not been successfully configured"
-			echo "SecretKey has not been successfully configured" >> "$LAPSLOG"
+			echo "SecretKey has not been successfully configured" | tee -a "$LAPSLOG"
 		fi
 	else
-		echo "CryptKey and SecretKey Escrowed to Jamf successfully"
-		echo "Device serial is $serial"
-		echo "JAMF ID is $ID"
-		echo "LAPS Configuration was successful"
-		echo "CryptKey and SecretKey Escrowed to Jamf successfully" >> "$LAPSLOG"
-		echo "Device serial is $serial" >> "$LAPSLOG"
-		echo "JAMF ID is $ID" >> "$LAPSLOG"
-		echo "LAPS Configuration was successful" >> "$LAPSLOG"
+		echo "CryptKey and SecretKey Escrowed to Jamf successfully" | tee -a "$LAPSLOG"
+		echo "Device serial is $serial" | tee -a "$LAPSLOG"
+		echo "JAMF ID is $ID" | tee -a "$LAPSLOG"
+		echo "LAPS Configuration was successful" | tee -a "$LAPSLOG"
 		RESULT="LAPS Configuration was successful"
 	fi
 
@@ -413,14 +403,12 @@ fi
 ############################################################################
 	
 	if [ -f $LaunchDFile ]; then
-		echo "LAPS Launch Daemon found. Removing old Launch Daemon."
-		echo "LAPS Launch Daemon found. Removing old Launch Daemon." >> $LAPSLOG
+		echo "LAPS Launch Daemon found. Removing old Launch Daemon." | tee -a "$LAPSLOG"
 	
 		rm -f $LaunchDFile
 		sleep 2
 	
-		echo "Launch Daemon removed. Completing rotation..."
-		echo "Launch Daemon removed. Completing rotation..." >> $LAPSLOG
+		echo "Launch Daemon removed." | tee -a "$LAPSLOG"
 	
 		#Create the plist
 		defaults write $LaunchDFile Label -string "com.LAPS.triggerCycle.plist"
@@ -429,7 +417,6 @@ fi
 		chown root:wheel $LaunchDFile
 		chmod 644 $LaunchDFile
 	else
-		echo "LAPS Launch Daemon not found. Completing setup..."
-		echo "LAPS Launch Daemon not found. Completing setup..." >> $LAPSLOG
+		echo "LAPS Launch Daemon not found" | tee -a "$LAPSLOG"
 	fi
 exit 0
