Update LAPS Create & Cycle Password Script

diff --git a/LAPS Create & Cycle Password Script b/LAPS Create & Cycle Password Script
--- a/LAPS Create & Cycle Password Script
+++ b/LAPS Create & Cycle Password Script
@@ -2,8 +2,8 @@
 #
 # Author  : Perry Driscoll - https://github.com/PezzaD84
 # Created : 31/1/2022
-# Updated : 29/6/2023
-# Version : v2.2.2
+# Updated : 12/7/2023
+# Version : v2.2.3
 #
 ############################################################################
 # Description:
@@ -38,6 +38,7 @@
 LAPSLOG="/Library/.LAPS/Logs/LAPS.log"
 DEVICE=`hostname`
 serial=$(system_profiler SPHardwareDataType | awk '/Serial Number/{print $4}')
+LaunchDFile="/Library/LaunchDaemons/com.LAPS.triggerCycle.plist"
 
 ############################################################################
 # API Credentials
@@ -238,34 +239,13 @@ if dscl . read /Groups/admin | grep $4; then
 		if echo $pswdCheck | grep eDSAuthFailed; then
 		echo "Password validation failed."
 		echo "Password validation failed." >> "$LAPSLOG"
-		exit 1
-		fi
+        exit 1
+		else
 		echo "Password validated"
 		echo "Password validated" >> "$LAPSLOG"
-		
+		fi
+        
 		rm -rf /Users/$4/Library/Keychains/*
-		
-	############################################################################	
-	# Check Password reset Extension attribute
-	############################################################################
-	
-		resetStatus=$(curl -s -X "GET" "$6/JSSResource/computers/serialnumber/$serial/subset/ExtensionAttributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i Reset | tr '"' ' ' | awk '{print $17}')	
-			
-			if [[ $resetStatus == "Yes" ]]; then
-				echo "LAPS Password has been reset. Resetting EA to default value"
-				echo "LAPS Password has been reset. Resetting EA to default value" >> "$LAPSLOG"
-				
-				resetID=$(curl -s -X "GET" "$6/JSSResource/computers/serialnumber/$serial/subset/ExtensionAttributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i Reset | tr ':' ' ' | tr ',' ' ' | awk '{print $2}')
-					
-					curl -s -X "PUT" "$6/JSSResource/computers/serialnumber/$serial/subset/extension_attributes" \
-					-H "Content-Type: application/xml" \
-					-H "Accept: application/xml" \
-					-H "Authorization:Bearer ${token}" \
-					-d "<computer><extension_attributes><extension_attribute><id>$resetID</id><name>LAPS Reset Password</name><type>String</type><value>No</value></extension_attribute></extension_attributes></computer>"
-					else
-					echo "EA to cycle LAPS password has not been specified"
-					echo "EA to cycle LAPS password has not been specified" >> "$LAPSLOG"
-			fi
 else
 	echo "$4 does not exist. Creating local admin now"
 	echo "$4 does not exist. Creating local admin now" >> "$LAPSLOG"
@@ -406,7 +386,7 @@ secretID=$(curl -s -X "GET" "$6/JSSResource/computers/serialnumber/$serial/subse
 if [[ $9 == "" ]]; then
 	echo "No slack URL configured"
 else
-	curl -X POST -H 'Content-type: application/json' \
+	curl -s -X POST -H 'Content-type: application/json' \
 	-d \
 	'{
 	"blocks": [
@@ -441,3 +421,29 @@ else
 }' \
 $9
 fi
+
+############################################################################	
+# Check Password reset LaunchD
+############################################################################
+	
+	if [ -f $LaunchDFile ]; then
+		echo "LAPS Launch Daemon found. Removing old Launch Daemon."
+		echo "LAPS Launch Daemon found. Removing old Launch Daemon." >> $LAPSLOG
+	
+		rm -f $LaunchDFile
+		sleep 2
+	
+		echo "Launch Daemon removed."
+		echo "Launch Daemon removed." >> $LAPSLOG
+	
+		#Create the plist
+		defaults write $LaunchDFile Label -string "com.LAPS.triggerCycle.plist"
+	
+		#Set ownership
+		chown root:wheel $LaunchDFile
+		chmod 644 $LaunchDFile
+	else
+		echo "LAPS Launch Daemon not found"
+		echo "LAPS Launch Daemon not found" >> $LAPSLOG
+	fi
+exit 0
