Update LAPS Decode Password Script

diff --git a/LAPS Decode Password Script b/LAPS Decode Password Script
--- a/LAPS Decode Password Script
+++ b/LAPS Decode Password Script
@@ -167,7 +167,21 @@ secretkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extensi
 ############################################################################
 # Decode password and display
 ############################################################################
-	
+
+if [[ $cryptkey == "" ]] || [[ $secretkey == "" ]]; then
+	echo "Aborting"
+	dialog \
+	--bannerimage "/Library/.LAPS/Branding/Wallpapers/GenericLapsBanner.png" \
+	--title "none" \
+	--icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns" \
+	--message "Device inventory not found. \n\nPlease make sure the device name is correct." \
+	--messagefont "name=Arial,size=17" \
+	--ontop \
+	--moveable \
+	--small
+	exit 1
+fi	
+
 passwd=$(echo $cryptkey | openssl enc -aes-256-cbc -md sha512 -a -d -salt -pass pass:$secretkey)
 				
 dialog \
