Update LAPS Decode Password Script

diff --git a/LAPS Decode Password Script b/LAPS Decode Password Script
--- a/LAPS Decode Password Script
+++ b/LAPS Decode Password Script
@@ -2,8 +2,8 @@
 #
 # Author  : Perry Driscoll - https://github.com/PezzaD84
 # Created : 31/1/2022
-# Updated : 25/9/2023
-# Version : v2.2.3
+# Updated : 26/9/2023
+# Version : v2.2.4
 #
 ############################################################################
 # Description:
@@ -51,8 +51,7 @@ else
 	touch "$LAPSLOG" 
 fi
 
-echo -e "=================================================================\n================ LAPS Decode `date '+%d/%m/%Y %T'` ================\n================================================================="
-echo -e "=================================================================\n================ LAPS Decode `date '+%d/%m/%Y %T'` ================\n=================================================================" >> "$LAPSLOG"
+echo -e "=================================================================\n================ LAPS Decode `date '+%d/%m/%Y %T'` ================\n=================================================================" | tee -a "$LAPSLOG"
 
 ##############################################################
 # Functions
@@ -91,27 +90,23 @@ DialogInstall(){
 
 if ! command -v dialog &> /dev/null
 then
-	echo "SwiftDialog is not installed. App will be installed now....."
-	echo "SwiftDialog is not installed. App will be installed now....." >> $LAPSLOG
+	echo "SwiftDialog is not installed. App will be installed now....." | tee -a "$LAPSLOG"
 	sleep 2
 	
 	DialogInstall
 	
 else
-	echo "SwiftDialog is installed. Checking installed version....."
-	echo "SwiftDialog is installed. Checking installed version....." >> $LAPSLOG
+	echo "SwiftDialog is installed. Checking installed version....." | tee -a "$LAPSLOG"
 	
 	installedVersion=$(dialog -v | sed 's/./ /6' | awk '{print $1}')
 	
 	latestVersion=$(curl -sfL "https://github.com/bartreardon/swiftDialog/releases/latest" | tr '"' "\n" | grep -i "expanded_assets" | head -1 | tr '/' ' ' | awk '{print $7}' | tr -d 'v')
 	
 	if [[ $installedVersion != $latestVersion ]]; then
-		echo "Dialog needs updating"
-		echo "Dialog needs updating" >> $LAPSLOG
+		echo "Dialog needs updating" | tee -a "$LAPSLOG"
 		DialogInstall
 	else
-		echo "Dialog is up to date. Continuing to assemble...."
-		echo "Dialog is up to date. Continuing to assemble...." >> $LAPSLOG
+		echo "Dialog is up to date. Continuing to assemble...." | tee -a "$LAPSLOG"
 	fi
 	sleep 3
 fi
@@ -150,38 +145,40 @@ reason=$(echo $message | awk -F '"Reason" : "' '{print$2}' | awk -F '"' '{print$
 if [[ $name == "" ]] || [[ $reason == "" ]]; then
 	echo "Aborting"
 	exit 1
-fi			
+fi
+
+name2=$(echo $name | sed -e 's#’#%E2%80%99#g' -e 's# #%20#g')
 
 ############################################################################
 # Grab decoder key for password
 ############################################################################
 	
-cryptkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i CryptKey | tr '"' ' ' | awk '{print $16}')
+cryptkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name2/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i CryptKey | tr '"' ' ' | awk '{print $16}')
 	
 ############################################################################			
 # Grab secret for decoder
 ############################################################################
 	
-secretkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i Secret | tr '"' ' ' | awk '{print $16}')
+secretkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name2/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i Secret | tr '"' ' ' | awk '{print $16}')
 
 ############################################################################
 # Decode password and display
 ############################################################################
 
-if [[ $cryptkey == "" ]] || [[ $secretkey == "" ]]; then
-	echo "Aborting"
-	dialog \
-	--bannerimage "/Library/.LAPS/Branding/Wallpapers/GenericLapsBanner.png" \
-	--title "none" \
-	--icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns" \
-	--message "Device inventory not found. \n\nPlease make sure the device name is correct." \
-	--messagefont "name=Arial,size=17" \
-	--ontop \
-	--moveable \
-	--small
-	exit 1
-fi	
-
+	if [[ $cryptkey == "" ]] || [[ $secretkey == "" ]]; then
+		echo "Aborting"
+		dialog \
+		--bannerimage "/Library/.LAPS/Branding/Wallpapers/GenericLapsBanner.png" \
+		--title "none" \
+		--icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns" \
+		--message "Device inventory not found. \n\nPlease make sure the device name is correct." \
+		--messagefont "name=Arial,size=17" \
+		--ontop \
+		--moveable \
+		--small
+		exit 1
+	fi
+	
 passwd=$(echo $cryptkey | openssl enc -aes-256-cbc -md sha512 -a -d -salt -pass pass:$secretkey)
 				
 dialog \
@@ -195,10 +192,8 @@ dialog \
 --moveable \
 --small &
 
-echo "The LAPS Password for $name was viewed by $CURRENT_USER on $DEVICE"
-echo "The LAPS Password for $name was viewed by $CURRENT_USER on $DEVICE" >> "$LAPSLOG"
-echo "Reason for viewing password: $reason"
-echo "Reason for viewing password: $reason" >> "$LAPSLOG"
+echo "The LAPS Password for $name was viewed by $CURRENT_USER on $DEVICE" | tee -a "$LAPSLOG"
+echo "Reason for viewing password: $reason" | tee -a "$LAPSLOG"
 
 ############################################################################
 # Slack notification
@@ -270,9 +265,7 @@ fi
 	
 	
 	if [[ $6 == "" ]]; then
-		
-		echo "Password rotation has not been set."
-		echo "Password rotation has not been set." >> "$LAPSLOG"
+		echo "Password rotation has not been set." | tee -a "$LAPSLOG"
 		
 	else
 		
@@ -289,19 +282,17 @@ fi
 		HOUR=$(echo $cycleTime | awk '{print $3}')
 		MINUTE=$(echo $cycleTime | awk '{print $4}')
 		
-		echo "Password rotation has been set to $6 Minutes. LAPS Password for $name will be reset at $HOUR:$MINUTE."
-		echo "Password rotation has been set to $6 Minutes. LAPS Password for $name will be reset at $HOUR:$MINUTE." >> "$LAPSLOG"
+		echo "Password rotation has been set to $6 Minutes. LAPS Password for $name will be reset at $HOUR:$MINUTE." | tee -a "$LAPSLOG"
 		
 		############################################################################
 		# Create plist to Cycle Password
 		############################################################################
 		
 		plist="/Library/LaunchDaemons/com.LAPS.triggerCycle.plist"
-
+		
 		# Bootout old Launch Daemon
 		launchctl bootout system $plist
-		sleep 2
-
+		
 		#Create the plist
 		defaults write $plist Label -string "com.LAPS.triggerCycle.plist"
 		
@@ -329,6 +320,7 @@ fi
 			echo "OS Version is 11 or older"
 			launchctl load $plist
 		fi
+		
 		sleep 5
 		
 	fi
